---
title: "UKB formatting and coding notes"
output: html_notebook
---

# Dates

## Main UKB dataset

### "ValueType" = "Date"

Field ID's of "ValueType" `Date` (e.g. [Field ID `40005`, "Date of cancer diagnosis"](https://biobank.ndph.ox.ac.uk/ukb/field.cgi?id=40005)) are recorded as `YYYY-MM-DD` (e.g. 1st February 2015 is recorded as: "2015-02-01"). 

In R, This can be converted from text to date with `as.Date('2015-02-01')`, and back to character using `as.character()`.

### "ValueType" == "Continuous"

Field ID's of "ValueType" `Continuous` (e.g. [Field ID `20008`, "Interpolated Year when non-cancer illness first diagnosed"](https://biobank.ndph.ox.ac.uk/ukb/field.cgi?id=20008)) can be converted to date type in R with, for example, `lubridate::as_date(lubridate::date_decimal(2000.5))`, which would convert to the date "2000-07-02".

### Special dates

Field IDs [20006](https://biobank.ndph.ox.ac.uk/ukb/field.cgi?id=20006) and [20008](https://biobank.ndph.ox.ac.uk/ukb/field.cgi?id=20008) (interpolated year when cancer/non-cancer first diagnosed, respectively) both use [data coding 13](https://biobank.ndph.ox.ac.uk/ukb/coding.cgi?id=13), where `-1` and `-3` indicate "Date uncertain or unknown" and "Preferred not to answer" respectively.

## Primary care data

Dates in the `event_dt` (diagnoses: `gp_clinical.txt`) and `issue_date` (prescriptions: `gp_scripts.txt`) columns are recorded as `DD/MM/YYYY` (e.g. "29/01/2001")

In R, This can be converted from text to date with `lubridate::dmy("29/01/2001")`. Converting this back to a string using `as.character()` would reformat to the following: "2001-01-29".

### Special dates

These are detailed in [resource 591](https://biobank.ndph.ox.ac.uk/ukb/refer.cgi?id=591):

| Date | Interpretation |
|------|----------------|
| 01/01/1901 | Clinical event or prescription date precedes participant date of birth |
| 02/02/1902 | Date matches participant date of birth |
| 03/03/1903 | Date follows participant date of birth but is in the year of their birth |
| 07/07/2037 | Date was in the future |
